### ISSUE TITLE
Bug: putting image from camera puts it in wrong orientation

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [daothanhduy305/KRichEditor#10]
See attached video:

[device-2018-02-12-154228.zip](https://github.com/daothanhduy305/KRichEditor/files/1716437/device-2018-02-12-154228.zip)

Is it possible to customize the way it uses the photo?
Maybe a URL to a server image instead?

**Comment by daothanhduy305** [comment]
I strongly believe the image from camera bug is nothing related to the editor since I have not implemented any function to image button. I have left it to devs to DIY. For image manipulation, please read the instructions again, I believe I included everything necessary there (either for URL or base64 use case). For other bugs/questions, I would look into next week after the holiday. Cheers!

**Comment by AndroidDeveloperLB** [comment]
"I have left it to devs to DIY"
Which devs? 
About URL, you mean this:

> editorFragment.getEditor().command(EditorButton.IMAGE, true (for local path - Base64)/false (for URL), path/URL: String)

If so, ok. Does the toolbar of the library allows me to handle the clicking, so that only after the image is ready to be used, I would call this ? Is that it:

> To set image action (on image button clicked if enabled):
> 
>   imageButtonAction = {
>       // Do your stuffs here (start image picker)
>   }

?

If I put a path, and export to HTML, does the HTML include the image within (embedded) ?

**Comment by daothanhduy305** [comment]
If you look at the demo, you'll see that the clicking handler part would start the picker/camera/whatever it is. And then you can call the command api on activity result. Yh, I know that it's a little bit complicated/not state of art.

**Comment by AndroidDeveloperLB** [comment]
Oh so it's not a part of the library, since you wish to grant flexibility of usage, right?
If so, that's fine. Just that what you used it buggy in what I've shown here. 
Why did you close the issue, if I've shown that it does exist? The demo has the bug, and not the library, but it's still a bug...

**Comment by daothanhduy305** [comment]
@AndroidDeveloperLB I see. My apology coz I thought it had been at your end. Yh, I will fix it for sure :wink:

**Comment by AndroidDeveloperLB** [comment]
Thank you.
I would have preferred the other issues fixed though.
That's just a demo issue, which might put a negative view of it, but you can always explain what you wrote to me.

**Comment by daothanhduy305** [comment]
@AndroidDeveloperLB and thank you very much for bug reports. I'm really eager to get back to my gear to fix them but it would be next week :unamused: (damnit holiday)

**Comment by AndroidDeveloperLB** [comment]
Thank you. 
I've noticed other issues on Quill, and reported about them there.
I hope they get fixed soon.

**Comment by daothanhduy305** [comment]
When I test on my device, somehow I don't have this behavior. Anyway, this might be the bug within the image picker lib I use for the demo. And by the way, I would comment out the cute cat image insertion 😺

**Comment by AndroidDeveloperLB** [comment]
If it is, you should fix it, by using correct orientation of the image produced.
I have, however, noticed the same issue on the Quill library:
https://github.com/quilljs/quill/issues/1957
