### ISSUE TITLE
Want to focus in the editor

### ISSUE THREAD

**Issue by anand-nineleaps** [daothanhduy305/KRichEditor#20]
So, after setting the content to the editor, need to focus the cursor at the end of the text and make the keyboard pop-up with the toolbar, but:

1.  editor.focus() not working on onInitialized
2. toolbar is overlapped by the soft keyboard and doesn't come on top of the soft keyboard.

**Comment by anand-nineleaps** [comment]
If setting content with a blank or null string, the toolbar works fine.

**Comment by anand-nineleaps** [comment]
@daothanhduy305  @RahulSDeshpande can you help regarding this?

**Comment by RahulSDeshpande** [comment]
@anand-viswanath
I see, let me check it once & come back to you :)

**Comment by anand-viswanath** [comment]
> @anand-viswanath
> I see, let me check it once & come back to you :)

**Comment by anand-nineleaps** [comment]
@RahulSDeshpande So, somehow I figured the toolbar issue, so that's sorted. But still, need little help regarding the editor.focus().

**Comment by anand-nineleaps** [comment]
@RahulSDeshpande @daothanhduy305 Any update for this?

**Comment by daothanhduy305** [comment]
> @RahulSDeshpande @daothanhduy305 Any update for this?
> 
> 

Will try to look into it this weekend :)

**Comment by anand-nineleaps** [comment]
@daothanhduy305  any updates?

**Comment by daothanhduy305** [comment]
> @daothanhduy305  any updates?

You can get the latest build via jitpack. I will bump the version later.

Now you can call focus the way you want in onInitialized and have the focus along w keyboard pop out (as a param to editor.focus method)
