### ISSUE TITLE
Bug: alignment doesn't affect list accordingly

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [daothanhduy305/KRichEditor#4]
Steps:
1. Write in RTL language (Hebrew for example)
2. Make it in a list (bullets/numbers)
3. align to right.

The bug:
The marks of the list (bullets/numbers) do not align to the right of the text. Instead, they are on the left of the text.

See here:

![image](https://user-images.githubusercontent.com/5357526/36074015-75b0dc12-0f42-11e8-9be4-3f4b2e7ead53.png)

**Comment by daothanhduy305** [comment]
Closed and more info at #5.

**Comment by AndroidDeveloperLB** [comment]
Yes, this is the new bug report:
https://github.com/quilljs/quill/issues/1956
