### ISSUE TITLE
Question: is it possible to have checkboxes like bullets/numbers list?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [daothanhduy305/KRichEditor#6]
Those can be checked/unchecked, like a to-do list.

**Comment by AndroidDeveloperLB** [comment]
Why close it?
Was it added?

**Comment by daothanhduy305** [comment]
Yes, look at the commit I referenced and you'll see. However it would take time to be released. For now, just get it from jitpack :wink:

**Comment by AndroidDeveloperLB** [comment]
Please let this issue open till it's really available, so that I can try it out...

**Comment by daothanhduy305** [comment]
To have the latest (commit) build, in your project gradle:

    allprojects {
      repositories {
          google()
          jcenter()
          ...
          maven { url 'https://jitpack.io' } // Use this instead
          ...
          }
    }

And then in your app gradle:

    dependencies {
        compile 'com.github.daothanhduy305:KRichEditor:-SNAPSHOT'
    }

To prevent gradle from caching builds, add this to your gradle:

    configurations.all {
        resolutionStrategy.cacheChangingModulesFor 0, 'seconds'
    }
